### ISSUE TITLE
Works great apart from when using gmail

### ISSUE THREAD

**Issue by jackttcoms** [snipworks/php-smtp#8]
It was not working with gmail but then i used my own and it worked great! Love this script! So lightweight!

**Comment by snipworks** [comment]
For gmail smtp, I recommend to use TLS protocol with port 587. See the `example/send.php` file.
Please take note that using your own password in gmail may not work as expected.
Its better to create application specific password and/or enable less secure apps.

https://support.google.com/cloudidentity/answer/6260879?hl=en
https://support.google.com/accounts/answer/185833?hl=en
