### ISSUE TITLE
when sending emails to more than one person，The recipient show only the first one

### ISSUE THREAD

**Issue by yoonper** [snipworks/php-smtp#9]
When sending emails to more than one person，the recipient show only the first one
line 452  $delimiter = ', ' . self::CRLF;
remove self::CRLF

**Comment by snipworks** [comment]
@yoonper Thank you for this issue. I've already fixed it and created a new release 🙇
Pull Request #10
Release v2.0.1 - https://github.com/snipworks/php-smtp/releases/tag/v2.0.1
